index: "1"
sensor_sn: "000085114212"
fps: "30"                   # 5, 15, and 30
color_resolution: 1536P   # 720P, 1080P, 1440P, 1536P, 2160P, 3072P

depth_enabled: "true"
depth_mode: NFOV_UNBINNED # NFOV_UNBINNED, NFOV_2X2BINNED, WFOV_UNBINNED, WFOV_2X2BINNED, and PASSIVE_IR
depth_unit: 16UC1         # "32FC1" (32 bit float metre) or "16UC1" (16 bit integer millimetre)


color_enabled: "true"
color_format: bgra        # bgra, jpeg


point_cloud: "true"
rgb_point_cloud: "true"
point_cloud_in_depth_frame: "false"
recording_file: ""
recording_loop_enabled: "false"
body_tracking_enabled: "false"
body_tracking_smoothing_factor: "0.0"
rescale_ir_to_mono8: "false"
ir_mono8_scaling_factor: "1.0"
imu_rate_target: "0"
wired_sync_mode: "0"
subordinate_delay_off_master_usec: "0"